apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  MYSQL_HOST: {{ .Values.database.db_host | b64enc  }}
  MYSQL_PORT: {{ .Values.database.db_port | b64enc  }}
  MYSQL_USER: {{ .Values.database.db_user | b64enc  }}
  MYSQL_PASSWORD: {{ .Values.database.db_pass | b64enc }}
  MYSQL_DATABASE: {{ .Values.database.db_database | b64enc }}
