{{- if and .Values.ingress.tls .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secname  }}
  namespace: {{ .Values.ingress.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get "www.devopszero.id.vn/cert.pem"  | b64enc }}
  tls.key: {{ $.Files.Get "www.devopszero.id.vn/privkey.pem"  | b64enc }}
{{- end }}

